# Google App Engine configuration
runtime: python312

env_variables:
  FLASK_ENV: production
  DATABASE_URL: postgresql://username:password@/dbname?host=/cloudsql/project:region:instance
  REDIS_URL: redis://redis-instance:6379/0
  SECRET_KEY: your-production-secret-key
  COINGECKO_REQUEST_DELAY: "1.5"
  COINGECKO_CACHE_TTL: "300"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

vpc_access_connector:
  name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME
