version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: homyak109
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      bash -c "
        until pg_isready -h db -p 5432 -U youruser; do sleep 1; done
        && python create_db.py
        && python init_admin.py
        && gunicorn --bind 0.0.0.0:5000 --workers 4 --threads 2 app:app
      "
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:homyak109@db:5432/database
      # другие переменные
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
