# Development overrides for docker-compose.yml
version: '3.8'

services:
  web:
    build:
      target: production
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - WEB_RELOAD=true
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.venv
    ports:
      - "5000:5000"
    command: >
      sh -c "
        python -m flask db upgrade &&
        python run.py
      "

  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev_password

  redis:
    ports:
      - "6379:6379"

  # Development-only services
  adminer:
    image: adminer:latest
    container_name: crypto_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - backend
    profiles:
      - development

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: crypto_redis_commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - backend
    profiles:
      - development
