version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: homyak109
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile        # ваш Dockerfile (копирует app.py, config.py и т.п.)
    container_name: diplom1_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # Обращаемся к БД через DNS-имя сервиса "db"
      DATABASE_URL: "postgresql://postgres:homyak109@db:5432/database"
      FLASK_ENV: development       # чтобы был включён DEBUG-режим
    ports:
      - "5000:5000"                 # если Flask слушает 0.0.0.0:5000
    volumes:
      - ./:/app                     # если хотите монтировать локальный код внутрь контейнера
    networks:
      - backend

networks:
  backend:
    driver: bridge
