[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "FLASK_ENV"
value = "production"

[[deploy.environmentVariables]]
name = "DATABASE_URL"
value = "${{Postgres.DATABASE_URL}}"

[[deploy.environmentVariables]]
name = "REDIS_URL"
value = "${{Redis.REDIS_URL}}"

[[deploy.environmentVariables]]
name = "SECRET_KEY"
value = "${{SECRET_KEY}}"

[[deploy.environmentVariables]]
name = "COINGECKO_REQUEST_DELAY"
value = "1.5"

[[deploy.environmentVariables]]
name = "COINGECKO_CACHE_TTL"
value = "300"
