"""Increase password_hash field length to 256

Revision ID: 4665882b9615
Revises: fcaf36de4af6
Create Date: 2025-09-15 03:30:39.638525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4665882b9615'
down_revision = 'fcaf36de4af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
