"""Add CoinGecko crypto models

Revision ID: b9c01cf59226
Revises: a30e6cd918d4
Create Date: 2025-09-24 03:15:29.936414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c01cf59226'
down_revision = 'a30e6cd918d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('fully_diluted_valuation', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('high_24h', sa.Float(), nullable=True),
    sa.Column('low_24h', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('price_change_percentage_24h', sa.Float(), nullable=True),
    sa.Column('price_change_percentage_7d', sa.Float(), nullable=True),
    sa.Column('price_change_percentage_30d', sa.Float(), nullable=True),
    sa.Column('market_cap_change_24h', sa.Float(), nullable=True),
    sa.Column('market_cap_change_percentage_24h', sa.Float(), nullable=True),
    sa.Column('circulating_supply', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('max_supply', sa.Float(), nullable=True),
    sa.Column('ath', sa.Float(), nullable=True),
    sa.Column('ath_change_percentage', sa.Float(), nullable=True),
    sa.Column('ath_date', sa.DateTime(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('atl_change_percentage', sa.Float(), nullable=True),
    sa.Column('atl_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_data', schema=None) as batch_op:
        batch_op.create_index('idx_coin_data_coin_id', ['coin_id'], unique=False)
        batch_op.create_index('idx_coin_data_last_updated', ['last_updated'], unique=False)
        batch_op.create_index('idx_coin_data_market_cap_rank', ['market_cap_rank'], unique=False)
        batch_op.create_index('idx_coin_data_symbol', ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_data_coin_id'), ['coin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_data_symbol'), ['symbol'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_id', 'timestamp', name='unique_coin_timestamp')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('idx_price_history_coin_timestamp', ['coin_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_coin_id'), ['coin_id'], unique=False)

    op.create_table('market_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_alerts', schema=None) as batch_op:
        batch_op.create_index('idx_market_alerts_coin_type', ['coin_id', 'alert_type'], unique=False)
        batch_op.create_index('idx_market_alerts_user_active', ['user_id', 'is_active'], unique=False)

    op.create_table('user_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'coin_id', name='unique_user_coin')
    )
    with op.batch_alter_table('user_watchlist', schema=None) as batch_op:
        batch_op.create_index('idx_user_watchlist_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_watchlist', schema=None) as batch_op:
        batch_op.drop_index('idx_user_watchlist_user_id')

    op.drop_table('user_watchlist')
    with op.batch_alter_table('market_alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_market_alerts_user_active')
        batch_op.drop_index('idx_market_alerts_coin_type')

    op.drop_table('market_alerts')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_coin_id'))
        batch_op.drop_index('idx_price_history_coin_timestamp')

    op.drop_table('price_history')
    with op.batch_alter_table('coin_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_data_symbol'))
        batch_op.drop_index(batch_op.f('ix_coin_data_coin_id'))
        batch_op.drop_index('idx_coin_data_symbol')
        batch_op.drop_index('idx_coin_data_market_cap_rank')
        batch_op.drop_index('idx_coin_data_last_updated')
        batch_op.drop_index('idx_coin_data_coin_id')

    op.drop_table('coin_data')
    # ### end Alembic commands ###
