"""empty message

Revision ID: fcaf36de4af6
Revises: 
Create Date: 2025-06-30 08:39:55.329685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fcaf36de4af6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tg_subscriptions')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tg_subscribed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tg_symbol', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tg_ma', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tg_period', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tg_period')
        batch_op.drop_column('tg_ma')
        batch_op.drop_column('tg_symbol')
        batch_op.drop_column('is_tg_subscribed')

    op.create_table('tg_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ma', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('last_notified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tg_subscriptions_pkey')),
    sa.UniqueConstraint('chat_id', name=op.f('tg_subscriptions_chat_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
